export class BreakPointConstants {
  /**
   * Breakpoints that represent small device types.
   */
  public static readonly BREAKPOINT_SM: string = 'sm'
  /**
   * Breakpoints that represent middle device types.
   */
  public static readonly BREAKPOINT_MD: string = 'md'
  /**
   * Breakpoints that represent large device types.
   */
  public static readonly BREAKPOINT_LG: string = 'lg'
  /**
   * Grid row column list.
   */
  public static readonly grid_row_columns: number[] = [1, 2, 12]
  /**
   * Grid column span list.
   */
  public static readonly grid_column_spans: number[] = [1, 2, 3, 8, 12]
}