export class CommonConstants {
  /**
   * Full percent.
   */
  public static readonly FULL_PERCENT: string = '100%'
  /**
   * Indicates the maximum number of addresses returned by reverse geocoding query.
   */
  public static readonly MAX_ITEMS: number = 1
  /**
   * Font weight 500.
   */
  public static readonly FONT_WEIGHT_500: number = 500
  /**
   * Text opacity.
   */
  public static readonly TEXT_OPACITY: number[] = [1, 0.4, 0.6, 0.05]
  /**
   * Device types.
   */
  public static readonly DEVICE_TYPES: string[] = ['2in1', 'tablet'];
  /**
   * Bottom rect height.
   */
  public static readonly BOTTOM_RECT_HEIGHT: number = 24;
  /**
   * Tab bar height for sm and md.
   */
  public static readonly TAB_BAR_HEIGHT: number = 35;
}